"""Room-script interactable objects and hazards.

The 0x0100 interaction-record family: televisions, beds, healing machines,
PokeSpot plates, the Relic Stone, vending machines, fall hazards, and every
other press-A object a room script owns. See INTERACTABLE_OBJECTS.md.

Record format, fully characterized 2026-08-09 across all 241 records:

    common.rel interaction table, 0x1C stride
      +0x00  u8   method   1 and 2 fire on entry, 3 is press-A
      +0x02  u16  owning room id
      +0x07  u8   region index into the room's .ccd
      +0x08  u16  marker == 0x0100   (0x0596 is the common-script family)
      +0x0A  u16  index into the OWNING ROOM SCRIPT's function table
      +0x0E, +0x13, +0x17, +0x1B   parameters, zero in all but 7 records
      every other byte is zero in all 241

Two structural facts, measured rather than assumed:

- **Several records may share one (room, function).** Six pairs do; room
  0x54 function 11 has eight, one per region. Two televisions running
  `watch_tv` are therefore distinct objects, and identity must not collapse
  them.
- **No (room, region) carries two 0x0100 records**, but three (room,
  region) pairs are shared with the 0x0596 family. So the record index is
  the identity, not the region.

What is published, and what is not
----------------------------------
| Method | Classified | Published as |
|---|---|---|
| 3 (press A) | yes | `interact`, with the class's label |
| 3 (press A) | no | `interact`, labelled "Interactable" |
| 1 / 2 (on entry) | hazard class | `hazard` |
| 1 / 2 (on entry) | anything else | **nothing** |

An unclassified press-A record still publishes, because the record itself
proves the engine dispatches a room handler when the player interacts
there -- that is a fact about the world, and "Interactable" is the absence
of a label rather than a guessed one. An unclassified walk-in record does
NOT publish: those are cutscene and battle triggers, and calling one a
destination would invite a blind player to walk into it.
"""
from dataclasses import dataclass
import json

from .entities import Entity
from .interactable_roles import (
    GENERIC_LABEL, HAZARD_CLASSES, LABELS, PRESS_A_METHOD,
)
from .memory import MemoryError as GameMemoryError
from .npc_beacons import Position
from .region_geometry import parse_regions

HAZARD_CATEGORY = "hazard"
INTERACT_CATEGORY = "interact"


@dataclass(frozen=True)
class InteractableRecord:
    index: int
    room_id: int
    region_index: int
    method: int
    handler: str
    semantic: object

    @property
    def is_hazard(self):
        return self.semantic in HAZARD_CLASSES

    @property
    def is_press_a(self):
        return self.method == PRESS_A_METHOD

    @property
    def category(self):
        return HAZARD_CATEGORY if self.is_hazard else INTERACT_CATEGORY

    @property
    def label(self):
        return LABELS.get(self.semantic, GENERIC_LABEL)

    @property
    def identity(self):
        """The common.rel record index -- globally unique, and the same
        choice the warp sources make. Deliberately not (room, region):
        three (room, region) pairs are shared with the 0x0596 family."""
        return ("interact", self.index)

    @property
    def publishable(self):
        return self.is_press_a or self.is_hazard


def load_records(path):
    """Read the generated classification asset.

    Generated by `build_interactable_table.py` from the extracted room
    scripts; never hand-maintained. A missing or unreadable asset disables
    the source rather than degrading it."""
    with open(path, "r", encoding="utf-8") as handle:
        raw = json.load(handle)
    records = []
    for index, entry in raw.items():
        records.append(InteractableRecord(
            index=int(index),
            room_id=int(entry["room"]),
            region_index=int(entry["region"]),
            method=int(entry["method"]),
            handler=entry.get("handler"),
            semantic=entry.get("class"),
        ))
    return tuple(sorted(records, key=lambda record: record.index))


class RoomScriptInteractableSource:
    """Entity source for room-script objects, or for their hazards.

    Separate category-filtered instances publish press-A objects and hazards,
    so the navigator's categories stay independent while the record parsing,
    geometry, and state model exist once."""

    def __init__(self, memory, profile, pose_source, records, collision_dir,
                 room_codes, category=INTERACT_CATEGORY, logger=None):
        self.memory = memory
        self.profile = profile
        self.pose_source = pose_source
        self.records = tuple(records)
        self.collision_dir = collision_dir
        self.room_codes = dict(room_codes)
        self.category = category
        self.logger = logger
        self._regions = {}
        self._by_room = {}
        for record in sorted(self.records, key=lambda r: r.index):
            if record.publishable and record.category == category:
                self._by_room.setdefault(record.room_id, []).append(record)

    def player_pose(self):
        return self.pose_source.player_pose()

    def _room_regions(self, room_id):
        """Static geometry, cached for the process. The audit's rule:
        geometry may be cached indefinitely, live state may not."""
        if room_id in self._regions:
            return self._regions[room_id]
        regions = {}
        code = self.room_codes.get(room_id)
        if code:
            path = self.collision_dir / f"{code}.ccd"
            if path.exists():
                try:
                    regions = parse_regions(path.read_bytes())
                except Exception as error:
                    if self.logger is not None:
                        self.logger.debug(
                            "INTERACTABLES %s geometry unreadable: %r",
                            code, error)
                    regions = {}
        self._regions[room_id] = regions
        return regions

    def entities(self):
        try:
            room_id = self.memory.u16(
                self.profile.current_floor_id, "interactable room id")
        except GameMemoryError:
            return []
        records = self._by_room.get(room_id)
        if not records:
            return []
        regions = self._room_regions(room_id)
        if not regions:
            return []
        pose = self.player_pose()
        result = []
        for record in records:
            region = regions.get(record.region_index)
            if region is None:
                # The record names a region this room's geometry does not
                # contain. Publishing it would mean announcing a direction
                # derived from nothing.
                if self.logger is not None:
                    self.logger.debug(
                        "INTERACTABLES record %d names missing region %d in "
                        "room 0x%02X", record.index, record.region_index,
                        room_id)
                continue
            nearest = region.nearest_point(pose.position.x, pose.position.z)
            if nearest is None:
                continue
            position = Position(nearest[0], region.anchor[1], nearest[1])
            result.append(Entity(
                category=record.category,
                identity=record.identity,
                label=record.label,
                position=position,
                # No interaction radius is published. These are region
                # triggers, not `peopleTalkCheck` targets, so there is no
                # three-term threshold to report -- and a hazard must never
                # be told it is "available".
                interaction_distance=None,
                subtype=record.semantic,
                metadata={
                    "handler": record.handler,
                    "region_index": record.region_index,
                    "record_index": record.index,
                    "method": record.method,
                    "anchor": Position(*region.anchor),
                    "interaction_position": position,
                    # Hazards are warnings. Nothing about them should
                    # invite the player to walk over.
                    "beacon": not record.is_hazard,
                    "hazard": record.is_hazard,
                },
            ))
        return result
